apiVersion: apps/v1
kind: Deployment
metadata:
  name: richard-deployment
  labels:
    app: richardapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: richardapp
  template:
    metadata:
      labels:
        app: richardapp
    spec:
      containers:
      - name: richard-container
        image: qiaowenz/myapp33:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: richardapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: richardapp 
