# Workflow to deploy the artifacts
name: cd
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
       - name: Deployment using docker
         run: |
           sudo docker rm -f webrichard
           sudo docker rmi -f qiaowenz/myapp33:latest
           sudo docker run -dt --name webrichard -p 9090:8080 qiaowenz/myapp33:latest
